-- Auto-generated 2026-08-03 — LIVE knickgasm.com collections (59) from the public
-- Shopify endpoint /collections.json, seeded for US/UK/Global markets.
INSERT INTO public.knickgasm_collections (market, handle, title, description, url) VALUES
  ('US', 'above-20-000', 'Above ₹20,000', '', 'https://knickgasm.com/collections/above-20-000'),
  ('US', 'accessories', 'Accessories', '', 'https://knickgasm.com/collections/accessories'),
  ('US', 'adidas-sambas', 'Adidas sambas', '', 'https://knickgasm.com/collections/adidas-sambas'),
  ('US', 'aesthetic', 'Aesthetic', '', 'https://knickgasm.com/collections/aesthetic'),
  ('US', 'butterfly', 'Butterfly', '', 'https://knickgasm.com/collections/butterfly'),
  ('US', 'cartoon', 'Cartoon', '', 'https://knickgasm.com/collections/cartoon'),
  ('US', 'celebrity', 'Celebrity', '', 'https://knickgasm.com/collections/celebrity'),
  ('US', 'city-and-skyscrapers', 'City and Skyscrapers', '', 'https://knickgasm.com/collections/city-and-skyscrapers'),
  ('US', 'concert-collection', 'Concert Collection', '', 'https://knickgasm.com/collections/concert-collection'),
  ('US', 'converse-all-star', 'Converse all star', '', 'https://knickgasm.com/collections/converse-all-star'),
  ('US', 'converse-chuck-a-taylor', 'Converse chuck a taylor', '', 'https://knickgasm.com/collections/converse-chuck-a-taylor'),
  ('US', 'adidas-custom-shoes', 'Custom x Adidas', '', 'https://knickgasm.com/collections/adidas-custom-shoes'),
  ('US', 'anime-design-shoes', 'Custom x Anime', '', 'https://knickgasm.com/collections/anime-design-shoes'),
  ('US', 'bling', 'Custom x Bling', '', 'https://knickgasm.com/collections/bling'),
  ('US', 'custom-x-boots', 'Custom x Boots', '', 'https://knickgasm.com/collections/custom-x-boots'),
  ('US', 'cars', 'Custom x Cars', '', 'https://knickgasm.com/collections/cars'),
  ('US', 'coffee-air-forces', 'Custom x Coffee', '', 'https://knickgasm.com/collections/coffee-air-forces'),
  ('US', 'custom-converse-shoes', 'Custom x Converse', '', 'https://knickgasm.com/collections/custom-converse-shoes'),
  ('US', 'custom-denim-jacket', 'Custom x Denim Jacket', '', 'https://knickgasm.com/collections/custom-denim-jacket'),
  ('US', 'custom-x-football', 'Custom x Football', '', 'https://knickgasm.com/collections/custom-x-football'),
  ('US', 'custom-jordans', 'Custom x Jordans', '', 'https://knickgasm.com/collections/custom-jordans'),
  ('US', 'nike-air-force-1', 'Custom x Nike air force 1', '', 'https://knickgasm.com/collections/nike-air-force-1'),
  ('US', 'nike-court-vision', 'Custom x Nike court vision', '', 'https://knickgasm.com/collections/nike-court-vision'),
  ('US', 'custom-nike-shoes', 'Custom x Nikes', '', 'https://knickgasm.com/collections/custom-nike-shoes'),
  ('US', 'pets', 'Custom x Pets', '', 'https://knickgasm.com/collections/pets'),
  ('US', 'sports', 'Custom x Sports', '', 'https://knickgasm.com/collections/sports'),
  ('US', 'custom-x-taylor-swift', 'Custom x Taylor Swift', '', 'https://knickgasm.com/collections/custom-x-taylor-swift'),
  ('US', 'wedding', 'Custom x Wedding', '', 'https://knickgasm.com/collections/wedding'),
  ('US', 'customs-x-changeable-swooshes', 'Customs x Changeable Swooshes', '', 'https://knickgasm.com/collections/customs-x-changeable-swooshes'),
  ('US', 'demon-slayer', 'Demon Slayer', '', 'https://knickgasm.com/collections/demon-slayer'),
  ('US', 'dragon', 'Dragon', '', 'https://knickgasm.com/collections/dragon'),
  ('US', 'dragon-ball', 'Dragon Ball', '', 'https://knickgasm.com/collections/dragon-ball'),
  ('US', 'drip', 'Drip', '', 'https://knickgasm.com/collections/drip'),
  ('US', 'dyed', 'Dye''d', '', 'https://knickgasm.com/collections/dyed'),
  ('US', 'custom-embroidery-shoes', 'Embroidery', '', 'https://knickgasm.com/collections/custom-embroidery-shoes'),
  ('US', 'featured-products', 'Featured Products', '', 'https://knickgasm.com/collections/featured-products'),
  ('US', 'gaming', 'Gaming', '', 'https://knickgasm.com/collections/gaming'),
  ('US', 'jujustu-kaisen', 'Jujustu Kaisen', '', 'https://knickgasm.com/collections/jujustu-kaisen'),
  ('US', 'knickgasm-best-sellers', 'Knickgasm Bestsellers', '', 'https://knickgasm.com/collections/knickgasm-best-sellers'),
  ('US', 'mid-and-high-tops', 'Mid and High Tops', '', 'https://knickgasm.com/collections/mid-and-high-tops'),
  ('US', 'minimalist', 'Minimalist', '', 'https://knickgasm.com/collections/minimalist'),
  ('US', 'mismatched', 'Mismatched', '', 'https://knickgasm.com/collections/mismatched'),
  ('US', 'movie-and-tv-shows', 'Movie and Tv Shows', '', 'https://knickgasm.com/collections/movie-and-tv-shows'),
  ('US', 'naruto', 'Naruto', '', 'https://knickgasm.com/collections/naruto'),
  ('US', 'neon-and-uv', 'Neon and Uv', '', 'https://knickgasm.com/collections/neon-and-uv'),
  ('US', 'one-piece', 'One Piece', '', 'https://knickgasm.com/collections/one-piece'),
  ('US', 'pastel-design-shoes', 'Pastels', '', 'https://knickgasm.com/collections/pastel-design-shoes'),
  ('US', 'reflectives', 'Reflectives', '', 'https://knickgasm.com/collections/reflectives'),
  ('US', 'rope', 'Rope', '', 'https://knickgasm.com/collections/rope'),
  ('US', 'shop-all', 'Shop all', '', 'https://knickgasm.com/collections/shop-all'),
  ('US', 'singers-and-artists', 'Singers/Artists', '', 'https://knickgasm.com/collections/singers-and-artists'),
  ('US', 'spiderman-x-custom', 'Spiderman x Custom', '', 'https://knickgasm.com/collections/spiderman-x-custom'),
  ('US', 'splatter', 'Splatter', '', 'https://knickgasm.com/collections/splatter'),
  ('US', 'summer-collection', 'Summer collection', '', 'https://knickgasm.com/collections/summer-collection'),
  ('US', 'typography', 'Typography', '', 'https://knickgasm.com/collections/typography'),
  ('US', 'under-10-000', 'Under ₹10,000', '', 'https://knickgasm.com/collections/under-10-000'),
  ('US', 'under-15-000', 'Under ₹15,000', '', 'https://knickgasm.com/collections/under-15-000'),
  ('US', 'under-20-000', 'Under ₹20,000', '', 'https://knickgasm.com/collections/under-20-000'),
  ('US', 'universe-and-galaxy', 'Universe and Galaxy', '', 'https://knickgasm.com/collections/universe-and-galaxy'),
  ('UK', 'above-20-000', 'Above ₹20,000', '', 'https://knickgasm.com/collections/above-20-000'),
  ('UK', 'accessories', 'Accessories', '', 'https://knickgasm.com/collections/accessories'),
  ('UK', 'adidas-sambas', 'Adidas sambas', '', 'https://knickgasm.com/collections/adidas-sambas'),
  ('UK', 'aesthetic', 'Aesthetic', '', 'https://knickgasm.com/collections/aesthetic'),
  ('UK', 'butterfly', 'Butterfly', '', 'https://knickgasm.com/collections/butterfly'),
  ('UK', 'cartoon', 'Cartoon', '', 'https://knickgasm.com/collections/cartoon'),
  ('UK', 'celebrity', 'Celebrity', '', 'https://knickgasm.com/collections/celebrity'),
  ('UK', 'city-and-skyscrapers', 'City and Skyscrapers', '', 'https://knickgasm.com/collections/city-and-skyscrapers'),
  ('UK', 'concert-collection', 'Concert Collection', '', 'https://knickgasm.com/collections/concert-collection'),
  ('UK', 'converse-all-star', 'Converse all star', '', 'https://knickgasm.com/collections/converse-all-star'),
  ('UK', 'converse-chuck-a-taylor', 'Converse chuck a taylor', '', 'https://knickgasm.com/collections/converse-chuck-a-taylor'),
  ('UK', 'adidas-custom-shoes', 'Custom x Adidas', '', 'https://knickgasm.com/collections/adidas-custom-shoes'),
  ('UK', 'anime-design-shoes', 'Custom x Anime', '', 'https://knickgasm.com/collections/anime-design-shoes'),
  ('UK', 'bling', 'Custom x Bling', '', 'https://knickgasm.com/collections/bling'),
  ('UK', 'custom-x-boots', 'Custom x Boots', '', 'https://knickgasm.com/collections/custom-x-boots'),
  ('UK', 'cars', 'Custom x Cars', '', 'https://knickgasm.com/collections/cars'),
  ('UK', 'coffee-air-forces', 'Custom x Coffee', '', 'https://knickgasm.com/collections/coffee-air-forces'),
  ('UK', 'custom-converse-shoes', 'Custom x Converse', '', 'https://knickgasm.com/collections/custom-converse-shoes'),
  ('UK', 'custom-denim-jacket', 'Custom x Denim Jacket', '', 'https://knickgasm.com/collections/custom-denim-jacket'),
  ('UK', 'custom-x-football', 'Custom x Football', '', 'https://knickgasm.com/collections/custom-x-football'),
  ('UK', 'custom-jordans', 'Custom x Jordans', '', 'https://knickgasm.com/collections/custom-jordans'),
  ('UK', 'nike-air-force-1', 'Custom x Nike air force 1', '', 'https://knickgasm.com/collections/nike-air-force-1'),
  ('UK', 'nike-court-vision', 'Custom x Nike court vision', '', 'https://knickgasm.com/collections/nike-court-vision'),
  ('UK', 'custom-nike-shoes', 'Custom x Nikes', '', 'https://knickgasm.com/collections/custom-nike-shoes'),
  ('UK', 'pets', 'Custom x Pets', '', 'https://knickgasm.com/collections/pets'),
  ('UK', 'sports', 'Custom x Sports', '', 'https://knickgasm.com/collections/sports'),
  ('UK', 'custom-x-taylor-swift', 'Custom x Taylor Swift', '', 'https://knickgasm.com/collections/custom-x-taylor-swift'),
  ('UK', 'wedding', 'Custom x Wedding', '', 'https://knickgasm.com/collections/wedding'),
  ('UK', 'customs-x-changeable-swooshes', 'Customs x Changeable Swooshes', '', 'https://knickgasm.com/collections/customs-x-changeable-swooshes'),
  ('UK', 'demon-slayer', 'Demon Slayer', '', 'https://knickgasm.com/collections/demon-slayer'),
  ('UK', 'dragon', 'Dragon', '', 'https://knickgasm.com/collections/dragon'),
  ('UK', 'dragon-ball', 'Dragon Ball', '', 'https://knickgasm.com/collections/dragon-ball'),
  ('UK', 'drip', 'Drip', '', 'https://knickgasm.com/collections/drip'),
  ('UK', 'dyed', 'Dye''d', '', 'https://knickgasm.com/collections/dyed'),
  ('UK', 'custom-embroidery-shoes', 'Embroidery', '', 'https://knickgasm.com/collections/custom-embroidery-shoes'),
  ('UK', 'featured-products', 'Featured Products', '', 'https://knickgasm.com/collections/featured-products'),
  ('UK', 'gaming', 'Gaming', '', 'https://knickgasm.com/collections/gaming'),
  ('UK', 'jujustu-kaisen', 'Jujustu Kaisen', '', 'https://knickgasm.com/collections/jujustu-kaisen'),
  ('UK', 'knickgasm-best-sellers', 'Knickgasm Bestsellers', '', 'https://knickgasm.com/collections/knickgasm-best-sellers'),
  ('UK', 'mid-and-high-tops', 'Mid and High Tops', '', 'https://knickgasm.com/collections/mid-and-high-tops'),
  ('UK', 'minimalist', 'Minimalist', '', 'https://knickgasm.com/collections/minimalist'),
  ('UK', 'mismatched', 'Mismatched', '', 'https://knickgasm.com/collections/mismatched'),
  ('UK', 'movie-and-tv-shows', 'Movie and Tv Shows', '', 'https://knickgasm.com/collections/movie-and-tv-shows'),
  ('UK', 'naruto', 'Naruto', '', 'https://knickgasm.com/collections/naruto'),
  ('UK', 'neon-and-uv', 'Neon and Uv', '', 'https://knickgasm.com/collections/neon-and-uv'),
  ('UK', 'one-piece', 'One Piece', '', 'https://knickgasm.com/collections/one-piece'),
  ('UK', 'pastel-design-shoes', 'Pastels', '', 'https://knickgasm.com/collections/pastel-design-shoes'),
  ('UK', 'reflectives', 'Reflectives', '', 'https://knickgasm.com/collections/reflectives'),
  ('UK', 'rope', 'Rope', '', 'https://knickgasm.com/collections/rope'),
  ('UK', 'shop-all', 'Shop all', '', 'https://knickgasm.com/collections/shop-all'),
  ('UK', 'singers-and-artists', 'Singers/Artists', '', 'https://knickgasm.com/collections/singers-and-artists'),
  ('UK', 'spiderman-x-custom', 'Spiderman x Custom', '', 'https://knickgasm.com/collections/spiderman-x-custom'),
  ('UK', 'splatter', 'Splatter', '', 'https://knickgasm.com/collections/splatter'),
  ('UK', 'summer-collection', 'Summer collection', '', 'https://knickgasm.com/collections/summer-collection'),
  ('UK', 'typography', 'Typography', '', 'https://knickgasm.com/collections/typography'),
  ('UK', 'under-10-000', 'Under ₹10,000', '', 'https://knickgasm.com/collections/under-10-000'),
  ('UK', 'under-15-000', 'Under ₹15,000', '', 'https://knickgasm.com/collections/under-15-000'),
  ('UK', 'under-20-000', 'Under ₹20,000', '', 'https://knickgasm.com/collections/under-20-000'),
  ('UK', 'universe-and-galaxy', 'Universe and Galaxy', '', 'https://knickgasm.com/collections/universe-and-galaxy'),
  ('Global', 'above-20-000', 'Above ₹20,000', '', 'https://knickgasm.com/collections/above-20-000'),
  ('Global', 'accessories', 'Accessories', '', 'https://knickgasm.com/collections/accessories'),
  ('Global', 'adidas-sambas', 'Adidas sambas', '', 'https://knickgasm.com/collections/adidas-sambas'),
  ('Global', 'aesthetic', 'Aesthetic', '', 'https://knickgasm.com/collections/aesthetic'),
  ('Global', 'butterfly', 'Butterfly', '', 'https://knickgasm.com/collections/butterfly'),
  ('Global', 'cartoon', 'Cartoon', '', 'https://knickgasm.com/collections/cartoon'),
  ('Global', 'celebrity', 'Celebrity', '', 'https://knickgasm.com/collections/celebrity'),
  ('Global', 'city-and-skyscrapers', 'City and Skyscrapers', '', 'https://knickgasm.com/collections/city-and-skyscrapers'),
  ('Global', 'concert-collection', 'Concert Collection', '', 'https://knickgasm.com/collections/concert-collection'),
  ('Global', 'converse-all-star', 'Converse all star', '', 'https://knickgasm.com/collections/converse-all-star'),
  ('Global', 'converse-chuck-a-taylor', 'Converse chuck a taylor', '', 'https://knickgasm.com/collections/converse-chuck-a-taylor'),
  ('Global', 'adidas-custom-shoes', 'Custom x Adidas', '', 'https://knickgasm.com/collections/adidas-custom-shoes'),
  ('Global', 'anime-design-shoes', 'Custom x Anime', '', 'https://knickgasm.com/collections/anime-design-shoes'),
  ('Global', 'bling', 'Custom x Bling', '', 'https://knickgasm.com/collections/bling'),
  ('Global', 'custom-x-boots', 'Custom x Boots', '', 'https://knickgasm.com/collections/custom-x-boots'),
  ('Global', 'cars', 'Custom x Cars', '', 'https://knickgasm.com/collections/cars'),
  ('Global', 'coffee-air-forces', 'Custom x Coffee', '', 'https://knickgasm.com/collections/coffee-air-forces'),
  ('Global', 'custom-converse-shoes', 'Custom x Converse', '', 'https://knickgasm.com/collections/custom-converse-shoes'),
  ('Global', 'custom-denim-jacket', 'Custom x Denim Jacket', '', 'https://knickgasm.com/collections/custom-denim-jacket'),
  ('Global', 'custom-x-football', 'Custom x Football', '', 'https://knickgasm.com/collections/custom-x-football'),
  ('Global', 'custom-jordans', 'Custom x Jordans', '', 'https://knickgasm.com/collections/custom-jordans'),
  ('Global', 'nike-air-force-1', 'Custom x Nike air force 1', '', 'https://knickgasm.com/collections/nike-air-force-1'),
  ('Global', 'nike-court-vision', 'Custom x Nike court vision', '', 'https://knickgasm.com/collections/nike-court-vision'),
  ('Global', 'custom-nike-shoes', 'Custom x Nikes', '', 'https://knickgasm.com/collections/custom-nike-shoes'),
  ('Global', 'pets', 'Custom x Pets', '', 'https://knickgasm.com/collections/pets'),
  ('Global', 'sports', 'Custom x Sports', '', 'https://knickgasm.com/collections/sports'),
  ('Global', 'custom-x-taylor-swift', 'Custom x Taylor Swift', '', 'https://knickgasm.com/collections/custom-x-taylor-swift'),
  ('Global', 'wedding', 'Custom x Wedding', '', 'https://knickgasm.com/collections/wedding'),
  ('Global', 'customs-x-changeable-swooshes', 'Customs x Changeable Swooshes', '', 'https://knickgasm.com/collections/customs-x-changeable-swooshes'),
  ('Global', 'demon-slayer', 'Demon Slayer', '', 'https://knickgasm.com/collections/demon-slayer'),
  ('Global', 'dragon', 'Dragon', '', 'https://knickgasm.com/collections/dragon'),
  ('Global', 'dragon-ball', 'Dragon Ball', '', 'https://knickgasm.com/collections/dragon-ball'),
  ('Global', 'drip', 'Drip', '', 'https://knickgasm.com/collections/drip'),
  ('Global', 'dyed', 'Dye''d', '', 'https://knickgasm.com/collections/dyed'),
  ('Global', 'custom-embroidery-shoes', 'Embroidery', '', 'https://knickgasm.com/collections/custom-embroidery-shoes'),
  ('Global', 'featured-products', 'Featured Products', '', 'https://knickgasm.com/collections/featured-products'),
  ('Global', 'gaming', 'Gaming', '', 'https://knickgasm.com/collections/gaming'),
  ('Global', 'jujustu-kaisen', 'Jujustu Kaisen', '', 'https://knickgasm.com/collections/jujustu-kaisen'),
  ('Global', 'knickgasm-best-sellers', 'Knickgasm Bestsellers', '', 'https://knickgasm.com/collections/knickgasm-best-sellers'),
  ('Global', 'mid-and-high-tops', 'Mid and High Tops', '', 'https://knickgasm.com/collections/mid-and-high-tops'),
  ('Global', 'minimalist', 'Minimalist', '', 'https://knickgasm.com/collections/minimalist'),
  ('Global', 'mismatched', 'Mismatched', '', 'https://knickgasm.com/collections/mismatched'),
  ('Global', 'movie-and-tv-shows', 'Movie and Tv Shows', '', 'https://knickgasm.com/collections/movie-and-tv-shows'),
  ('Global', 'naruto', 'Naruto', '', 'https://knickgasm.com/collections/naruto'),
  ('Global', 'neon-and-uv', 'Neon and Uv', '', 'https://knickgasm.com/collections/neon-and-uv'),
  ('Global', 'one-piece', 'One Piece', '', 'https://knickgasm.com/collections/one-piece'),
  ('Global', 'pastel-design-shoes', 'Pastels', '', 'https://knickgasm.com/collections/pastel-design-shoes'),
  ('Global', 'reflectives', 'Reflectives', '', 'https://knickgasm.com/collections/reflectives'),
  ('Global', 'rope', 'Rope', '', 'https://knickgasm.com/collections/rope'),
  ('Global', 'shop-all', 'Shop all', '', 'https://knickgasm.com/collections/shop-all'),
  ('Global', 'singers-and-artists', 'Singers/Artists', '', 'https://knickgasm.com/collections/singers-and-artists'),
  ('Global', 'spiderman-x-custom', 'Spiderman x Custom', '', 'https://knickgasm.com/collections/spiderman-x-custom'),
  ('Global', 'splatter', 'Splatter', '', 'https://knickgasm.com/collections/splatter'),
  ('Global', 'summer-collection', 'Summer collection', '', 'https://knickgasm.com/collections/summer-collection'),
  ('Global', 'typography', 'Typography', '', 'https://knickgasm.com/collections/typography'),
  ('Global', 'under-10-000', 'Under ₹10,000', '', 'https://knickgasm.com/collections/under-10-000'),
  ('Global', 'under-15-000', 'Under ₹15,000', '', 'https://knickgasm.com/collections/under-15-000'),
  ('Global', 'under-20-000', 'Under ₹20,000', '', 'https://knickgasm.com/collections/under-20-000'),
  ('Global', 'universe-and-galaxy', 'Universe and Galaxy', '', 'https://knickgasm.com/collections/universe-and-galaxy')
ON CONFLICT (market, handle) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, url=EXCLUDED.url;
