-- Auto-generated 2026-05-01 20:28 UTC
-- Live Knickgasm collections scraped from public Shopify endpoints
-- Run: paste into Supabase Dashboard -> SQL Editor

INSERT INTO public.knickgasm_collections (market, handle, title, description, url) VALUES
  ('US', 'coffee-collection', '#1 Rated Coffee Collection', '', 'https://www.knickgasm.com/collections/coffee-collection'),
  ('US', '2026-first-flush', '2026 First Flush', '', 'https://www.knickgasm.com/collections/2026-first-flush'),
  ('US', 'advent-calendar-2025', 'Advent Calendar 2025', '', 'https://www.knickgasm.com/collections/advent-calendar-2025'),
  ('US', 'all', 'All Products', '', 'https://www.knickgasm.com/collections/all'),
  ('US', 'back-to-school-save-20', 'Back to School – Save $20', '', 'https://www.knickgasm.com/collections/back-to-school-save-20'),
  ('US', 'back-to-school-save-40', 'Back to School – Save $40', '', 'https://www.knickgasm.com/collections/back-to-school-save-40'),
  ('US', 'best-sellers', 'Best Sellers', '', 'https://www.knickgasm.com/collections/best-sellers'),
  ('US', 'black-sneakers', 'Black Sneakers', '', 'https://www.knickgasm.com/collections/black-sneakers'),
  ('US', 'caffeinated-sneakers', 'Caffeinated Sneakers', '', 'https://www.knickgasm.com/collections/caffeinated-sneakers'),
  ('US', 'scuff-resistant-sneakers', 'Paint Free Sneakers', '', 'https://www.knickgasm.com/collections/scuff-resistant-sneakers'),
  ('US', 'kicks-sneakers', 'Kicks Sneakers', '', 'https://www.knickgasm.com/collections/kicks-sneakers'),
  ('US', 'sneakers-gifts', 'Daily Rituals', '', 'https://www.knickgasm.com/collections/sneakers-gifts'),
  ('US', 'deal-of-the-day', 'Deal of the day', '', 'https://www.knickgasm.com/collections/deal-of-the-day'),
  ('US', 'find-your-balance', 'Find Your Balance', '', 'https://www.knickgasm.com/collections/find-your-balance'),
  ('US', 'first-flush-2025', 'First Flush 2025', '', 'https://www.knickgasm.com/collections/first-flush-2025'),
  ('US', 'gifts-cards', 'Gifts Cards', '', 'https://www.knickgasm.com/collections/gifts-cards'),
  ('US', 'gift-under-30', 'Gifts under $30', '', 'https://www.knickgasm.com/collections/gift-under-30'),
  ('US', 'glassware', 'Glassware', '', 'https://www.knickgasm.com/collections/glassware'),
  ('US', 'green-sneakers', 'Green Sneakers', '', 'https://www.knickgasm.com/collections/green-sneakers'),
  ('US', 'themed-supplements', 'Themed Supplements', '', 'https://www.knickgasm.com/collections/themed-supplements'),
  ('US', 'themed-sneakers', 'Themed Sneakers', '', 'https://www.knickgasm.com/collections/themed-sneakers'),
  ('US', 'themed-sneaker-hand-painted', 'Themed Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/themed-sneaker-hand-painted'),
  ('US', 'iced-crafts', 'Iced Brews', '', 'https://www.knickgasm.com/collections/iced-crafts'),
  ('US', 'iced-sneaker', 'Bling Kickss', '', 'https://www.knickgasm.com/collections/iced-sneaker'),
  ('US', 'instant-sneaker', 'Instant Mixes', '', 'https://www.knickgasm.com/collections/instant-sneaker'),
  ('US', 'insulated-gear', 'Insulated Gear', '', 'https://www.knickgasm.com/collections/insulated-gear'),
  ('US', 'latte-instant-premix', 'Lattes', '', 'https://www.knickgasm.com/collections/latte-instant-premix'),
  ('US', 'sale', 'LIMITED TIME SALE', '', 'https://www.knickgasm.com/collections/sale'),
  ('US', 'limited-time-savings', 'Limited-Time Savings', '', 'https://www.knickgasm.com/collections/limited-time-savings'),
  ('US', 'hand-painted-sneakers', 'Hand-painted Sneakers', '', 'https://www.knickgasm.com/collections/hand-painted-sneakers'),
  ('US', 'hand-painted-sneakers-for-families', 'Hand-painted Sneakers for Families', '', 'https://www.knickgasm.com/collections/hand-painted-sneakers-for-families'),
  ('US', 'hand-painted-sneakers', 'Hand-painted Sneakers', '', 'https://www.knickgasm.com/collections/hand-painted-sneakers'),
  ('US', 'dunks', 'Dunks', '', 'https://www.knickgasm.com/collections/dunks'),
  ('US', 'new-arrivals', 'New Arrivals', '', 'https://www.knickgasm.com/collections/new-arrivals'),
  ('US', 'hightop-sneakers', 'Hightop Sneakers', '', 'https://www.knickgasm.com/collections/hightop-sneakers'),
  ('US', 'samplers', 'Samplers', '', 'https://www.knickgasm.com/collections/samplers'),
  ('US', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.knickgasm.com/collections/second-flush-2025'),
  ('US', 'best-selling-march-2026', 'Shop Our Most Popular Picks', '', 'https://www.knickgasm.com/collections/best-selling-march-2026'),
  ('US', 'one-of-one-sneakers', 'One of One Sneakers 2025', '', 'https://www.knickgasm.com/collections/one-of-one-sneakers'),
  ('US', 'one-of-one-sneakers-2026', 'One of One Sneakers 2026', '', 'https://www.knickgasm.com/collections/one-of-one-sneakers-2026'),
  ('US', 'spices', 'Single Origin Spices', '', 'https://www.knickgasm.com/collections/spices'),
  ('US', 'stainless-steel-gear', 'Stainless Steel Gear', '', 'https://www.knickgasm.com/collections/stainless-steel-gear'),
  ('US', 'lace-up-into-spring', 'Lace-up Into Spring 🌿', '', 'https://www.knickgasm.com/collections/lace-up-into-spring'),
  ('US', 'super-saver-bundles', 'Super Saver Bundles', '', 'https://www.knickgasm.com/collections/super-saver-bundles'),
  ('US', 'sneaker-wares', 'Sneaker Accessories', '', 'https://www.knickgasm.com/collections/sneaker-wares'),
  ('US', 'long-panel-sneaker-bags', 'Lace Sets', '', 'https://www.knickgasm.com/collections/long-panel-sneaker-bags'),
  ('US', 'sneaker-pods', 'Sneaker Pods', '', 'https://www.knickgasm.com/collections/sneaker-pods'),
  ('US', 'sneakers-by-form', 'Sneakers By Form', '', 'https://www.knickgasm.com/collections/sneakers-by-form'),
  ('US', 'sneakers-by-type', 'Sneakers By Type', '', 'https://www.knickgasm.com/collections/sneakers-by-type'),
  ('US', 'sneakers-more', 'Sneakers More', '', 'https://www.knickgasm.com/collections/sneakers-more'),
  ('US', 'gifts', 'The Sneaker Sets Loved Around The World', '', 'https://www.knickgasm.com/collections/gifts'),
  ('US', 'embroidery-sneakers', 'Embroidery Sneakers', '', 'https://www.knickgasm.com/collections/embroidery-sneakers'),
  ('US', 'white-sneakers', 'White Sneakers', '', 'https://www.knickgasm.com/collections/white-sneakers'),
  ('US', 'winter-sneakers', 'Winter Sneakers', '', 'https://www.knickgasm.com/collections/winter-sneakers'),
  ('UK', 'coffee-collection', '#1 Rated Coffee Collection', '', 'https://www.knickgasm.com/collections/coffee-collection'),
  ('UK', '2026-first-flush', '2026 First Flush', '', 'https://www.knickgasm.com/collections/2026-first-flush'),
  ('UK', 'advent-calendar', 'Advent Calendar 2025', '', 'https://www.knickgasm.com/collections/advent-calendar'),
  ('UK', 'all', 'All Products', '', 'https://www.knickgasm.com/collections/all'),
  ('UK', 'airbrush-goodness', 'airbrush-goodness', '', 'https://www.knickgasm.com/collections/airbrush-goodness'),
  ('UK', 'airforce-black-sneakers', 'Airforce Black Sneakers', '', 'https://www.knickgasm.com/collections/airforce-black-sneakers'),
  ('UK', 'airforce-second-flush', 'airforce-second-flush', '', 'https://www.knickgasm.com/collections/airforce-second-flush'),
  ('UK', 'assorted-sneaker-bags', 'Assorted Lace Sets', '', 'https://www.knickgasm.com/collections/assorted-sneaker-bags'),
  ('UK', 'assorted-gift-sampler-sets', 'assorted-gift-sampler-sets', '', 'https://www.knickgasm.com/collections/assorted-gift-sampler-sets'),
  ('UK', 'assorted-sampler-gifts', 'assorted-sampler-gifts', '', 'https://www.knickgasm.com/collections/assorted-sampler-gifts'),
  ('UK', 'assorted-sneaker-collection', 'assorted-sneaker-collection', '', 'https://www.knickgasm.com/collections/assorted-sneaker-collection'),
  ('UK', 'atimas-favorite-sneakers', 'atimas-favorite-sneakers', '', 'https://www.knickgasm.com/collections/atimas-favorite-sneakers'),
  ('UK', 'atimas-favourite-holiday-sneakers', 'atimas-favourite-holiday-sneakers', '', 'https://www.knickgasm.com/collections/atimas-favourite-holiday-sneakers'),
  ('UK', 'autumn-flush-black-sneakers', 'Autumn Flush Black Sneakers', '', 'https://www.knickgasm.com/collections/autumn-flush-black-sneakers'),
  ('UK', 'autumn-sneakers', 'autumn-sneakers', '', 'https://www.knickgasm.com/collections/autumn-sneakers'),
  ('UK', 'barbaras-favorite-sneakers', 'barbaras-favorite-sneakers', '', 'https://www.knickgasm.com/collections/barbaras-favorite-sneakers'),
  ('UK', 'barbenheimer', 'barbenheimer', '', 'https://www.knickgasm.com/collections/barbenheimer'),
  ('UK', 'best-sellers', 'Best Sellers', '', 'https://www.knickgasm.com/collections/best-sellers'),
  ('UK', 'bfcm-sale-advent', 'bfcm-sale-advent', '', 'https://www.knickgasm.com/collections/bfcm-sale-advent'),
  ('UK', 'bfcm-sale-sneakers', 'bfcm-sale-sneakers', '', 'https://www.knickgasm.com/collections/bfcm-sale-sneakers'),
  ('UK', 'bfcm-upto50', 'bfcm-upto50', '', 'https://www.knickgasm.com/collections/bfcm-upto50'),
  ('UK', 'black', 'Black', '', 'https://www.knickgasm.com/collections/black'),
  ('UK', 'black-sneaker-bags', 'Black Lace Sets', '', 'https://www.knickgasm.com/collections/black-sneaker-bags'),
  ('UK', 'black-sneakers', 'Black Sneakers', '', 'https://www.knickgasm.com/collections/black-sneakers'),
  ('UK', 'black-sneaker-hand-painted', 'Black Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/black-sneaker-hand-painted'),
  ('UK', 'black-friday-flat-30-off', 'black-friday-flat-30-off', '', 'https://www.knickgasm.com/collections/black-friday-flat-30-off'),
  ('UK', 'black-friday-sale-2023', 'black-friday-sale-2023', '', 'https://www.knickgasm.com/collections/black-friday-sale-2023'),
  ('UK', 'black-fruity', 'black-fruity', '', 'https://www.knickgasm.com/collections/black-fruity'),
  ('UK', 'black-medium', 'black-medium', '', 'https://www.knickgasm.com/collections/black-medium'),
  ('UK', 'black-nutty', 'black-nutty', '', 'https://www.knickgasm.com/collections/black-nutty'),
  ('UK', 'black-strong', 'black-strong', '', 'https://www.knickgasm.com/collections/black-strong'),
  ('UK', 'black-sneaker-smoky', 'black-sneaker-smoky', '', 'https://www.knickgasm.com/collections/black-sneaker-smoky'),
  ('UK', 'black-sneakers-code', 'black-sneakers-code', '', 'https://www.knickgasm.com/collections/black-sneakers-code'),
  ('UK', 'black-sneakers-hand-painted-fb', 'black-sneakers-hand-painted-fb', '', 'https://www.knickgasm.com/collections/black-sneakers-hand-painted-fb'),
  ('UK', 'black-sneakers-hand-painted-gm', 'black-sneakers-hand-painted-gm', '', 'https://www.knickgasm.com/collections/black-sneakers-hand-painted-gm'),
  ('UK', 'bof-bestsellers', 'bof-bestsellers', '', 'https://www.knickgasm.com/collections/bof-bestsellers'),
  ('UK', 'breakfast-sneakers', 'breakfast-sneakers', '', 'https://www.knickgasm.com/collections/breakfast-sneakers'),
  ('UK', 'build-your-own-bundle', 'build-your-own-bundle', '', 'https://www.knickgasm.com/collections/build-your-own-bundle'),
  ('UK', 'buy-2-get-1-holiday-special-offer', 'buy-2-get-1-holiday-special-offer', '', 'https://www.knickgasm.com/collections/buy-2-get-1-holiday-special-offer'),
  ('UK', 'scuff-resistant', 'scuff-resistant', '', 'https://www.knickgasm.com/collections/scuff-resistant'),
  ('UK', 'scuff-resistant-1', 'scuff-resistant-1', '', 'https://www.knickgasm.com/collections/scuff-resistant-1'),
  ('UK', 'scuff-resistant-sneakers', 'scuff-resistant-sneakers', '', 'https://www.knickgasm.com/collections/scuff-resistant-sneakers'),
  ('UK', 'canada-free-gift', 'canada-free-gift', '', 'https://www.knickgasm.com/collections/canada-free-gift'),
  ('UK', 'canada-products', 'canada-products', '', 'https://www.knickgasm.com/collections/canada-products'),
  ('UK', 'chrome', 'chrome', '', 'https://www.knickgasm.com/collections/chrome'),
  ('UK', 'celebrity-favourite-gifts', 'Celebrity Favourite Gifts', '', 'https://www.knickgasm.com/collections/celebrity-favourite-gifts'),
  ('UK', 'ceramic-range', 'ceramic-range', '', 'https://www.knickgasm.com/collections/ceramic-range'),
  ('UK', 'kicks-sneakers', 'Kicks Sneakers', '', 'https://www.knickgasm.com/collections/kicks-sneakers'),
  ('UK', 'kicks-sneaker-hand-painted', 'Kicks Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/kicks-sneaker-hand-painted'),
  ('UK', 'kicks-latte', 'kicks-latte', '', 'https://www.knickgasm.com/collections/kicks-latte'),
  ('UK', 'kicks-strong', 'kicks-strong', '', 'https://www.knickgasm.com/collections/kicks-strong'),
  ('UK', 'kicks-sneakers-code', 'kicks-sneakers-code', '', 'https://www.knickgasm.com/collections/kicks-sneakers-code'),
  ('UK', 'kicks-sneakers-hand-painted-fb', 'kicks-sneakers-hand-painted-fb', '', 'https://www.knickgasm.com/collections/kicks-sneakers-hand-painted-fb'),
  ('UK', 'kicks-sneakers-hand-painted-gm', 'kicks-sneakers-hand-painted-gm', '', 'https://www.knickgasm.com/collections/kicks-sneakers-hand-painted-gm'),
  ('UK', 'kicks-sneakers-medium', 'kicks-sneakers-medium', '', 'https://www.knickgasm.com/collections/kicks-sneakers-medium'),
  ('UK', 'kicks-sneakers-nutty', 'kicks-sneakers-nutty', '', 'https://www.knickgasm.com/collections/kicks-sneakers-nutty'),
  ('UK', 'kicks-sneakers-spicy', 'kicks-sneakers-spicy', '', 'https://www.knickgasm.com/collections/kicks-sneakers-spicy'),
  ('UK', 'christmas-gifts', 'Christmas Gifts', '', 'https://www.knickgasm.com/collections/christmas-gifts'),
  ('UK', 'christmas-sale', 'christmas-sale', '', 'https://www.knickgasm.com/collections/christmas-sale'),
  ('UK', 'cinnamon-specials', 'cinnamon-specials', '', 'https://www.knickgasm.com/collections/cinnamon-specials'),
  ('UK', 'cinnamon-sneakers', 'cinnamon-sneakers', '', 'https://www.knickgasm.com/collections/cinnamon-sneakers'),
  ('UK', 'classic-gifts', 'Classic Gifts', '', 'https://www.knickgasm.com/collections/classic-gifts'),
  ('UK', 'cocoa-specials', 'cocoa-specials', '', 'https://www.knickgasm.com/collections/cocoa-specials'),
  ('UK', 'coral', 'Coral', '', 'https://www.knickgasm.com/collections/coral'),
  ('UK', 'sale', 'Cyber Monday Sale', '', 'https://www.knickgasm.com/collections/sale'),
  ('UK', 'cyber-monday-sale-2023', 'Cyber Monday Sale 2023', '', 'https://www.knickgasm.com/collections/cyber-monday-sale-2023'),
  ('UK', 'jordan-first-flush-2023', 'Jordan First Flush - 2023', '', 'https://www.knickgasm.com/collections/jordan-first-flush-2023'),
  ('UK', 'jordan-second-flush', 'jordan-second-flush', '', 'https://www.knickgasm.com/collections/jordan-second-flush'),
  ('UK', 'jordan-sneakers-gm', 'jordan-sneakers-gm', '', 'https://www.knickgasm.com/collections/jordan-sneakers-gm'),
  ('UK', 'deal-of-the-day-hidden', 'deal-of-the-day-hidden', '', 'https://www.knickgasm.com/collections/deal-of-the-day-hidden'),
  ('UK', 'discount', 'discount', '', 'https://www.knickgasm.com/collections/discount'),
  ('UK', 'discount-collection', 'discount-collection', '', 'https://www.knickgasm.com/collections/discount-collection'),
  ('UK', 'dooars-black-sneakers', 'Dooars Black Sneakers', '', 'https://www.knickgasm.com/collections/dooars-black-sneakers'),
  ('UK', 'dooars-sneakers', 'Dooars Sneakers', '', 'https://www.knickgasm.com/collections/dooars-sneakers'),
  ('UK', 'drinkware-gifts', 'Drinkware Gifts', '', 'https://www.knickgasm.com/collections/drinkware-gifts'),
  ('UK', 'energy', 'energy', '', 'https://www.knickgasm.com/collections/energy'),
  ('UK', 'entire-sneaker-accessories', 'entire-sneaker-accessories', '', 'https://www.knickgasm.com/collections/entire-sneaker-accessories'),
  ('UK', 'fall-sale', 'fall-sale', '', 'https://www.knickgasm.com/collections/fall-sale'),
  ('UK', 'featured-products', 'featured-products', '', 'https://www.knickgasm.com/collections/featured-products'),
  ('UK', 'featured-sneakers', 'featured-sneakers', '', 'https://www.knickgasm.com/collections/featured-sneakers'),
  ('UK', 'find-your-balance', 'find-your-balance', '', 'https://www.knickgasm.com/collections/find-your-balance'),
  ('UK', 'first-flush-2025', 'First Flush 2025', '', 'https://www.knickgasm.com/collections/first-flush-2025'),
  ('UK', 'first-flush-2', 'first-flush-2', '', 'https://www.knickgasm.com/collections/first-flush-2'),
  ('UK', 'first-flush-2022', 'first-flush-2022', '', 'https://www.knickgasm.com/collections/first-flush-2022'),
  ('UK', 'founders-favorites', 'founders-favorites', '', 'https://www.knickgasm.com/collections/founders-favorites'),
  ('UK', 'functional-detox-ingredients', 'functional-detox-ingredients', '', 'https://www.knickgasm.com/collections/functional-detox-ingredients'),
  ('UK', 'germany-bestsellers', 'germany-bestsellers', '', 'https://www.knickgasm.com/collections/germany-bestsellers'),
  ('UK', 'gift-bundles', 'Gift Bundles', '', 'https://www.knickgasm.com/collections/gift-bundles'),
  ('UK', 'gift-cards', 'Gift Cards', '', 'https://www.knickgasm.com/collections/gift-cards'),
  ('UK', 'gift-bestsellers', 'gift-bestsellers', '', 'https://www.knickgasm.com/collections/gift-bestsellers'),
  ('UK', 'gifts-above-75', 'Gifts above 75', '', 'https://www.knickgasm.com/collections/gifts-above-75'),
  ('UK', 'gifts-between-25-and-50', 'Gifts between 25 and 50', '', 'https://www.knickgasm.com/collections/gifts-between-25-and-50'),
  ('UK', 'gifts-for-her', 'Gifts For Her', '', 'https://www.knickgasm.com/collections/gifts-for-her'),
  ('UK', 'gifts-under-30', 'Gifts Under $30', '', 'https://www.knickgasm.com/collections/gifts-under-30'),
  ('UK', 'gifts-under-25', 'Gifts Under 25', '', 'https://www.knickgasm.com/collections/gifts-under-25'),
  ('UK', 'gifts-between-50-and-75', 'gifts-between-50-and-75', '', 'https://www.knickgasm.com/collections/gifts-between-50-and-75'),
  ('UK', 'gifts-for-him', 'gifts-for-him', '', 'https://www.knickgasm.com/collections/gifts-for-him'),
  ('UK', 'gifts-under-15', 'gifts-under-15', '', 'https://www.knickgasm.com/collections/gifts-under-15'),
  ('UK', 'glassware', 'Glassware', '', 'https://www.knickgasm.com/collections/glassware'),
  ('UK', 'green', 'Green', '', 'https://www.knickgasm.com/collections/green'),
  ('UK', 'green-sneaker-bags', 'Green Lace Sets', '', 'https://www.knickgasm.com/collections/green-sneaker-bags'),
  ('UK', 'green-sneakers', 'Green Sneakers', '', 'https://www.knickgasm.com/collections/green-sneakers'),
  ('UK', 'green-sneakers-hand-painted', 'Green Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/green-sneakers-hand-painted'),
  ('UK', 'green-sneakers-code', 'green-sneakers-code', '', 'https://www.knickgasm.com/collections/green-sneakers-code'),
  ('UK', 'green-sneakers-gm', 'green-sneakers-gm', '', 'https://www.knickgasm.com/collections/green-sneakers-gm'),
  ('UK', 'green-sneakers-gm-1', 'green-sneakers-gm-1', '', 'https://www.knickgasm.com/collections/green-sneakers-gm-1'),
  ('UK', 'grocery-collection-page-manual', 'grocery-collection-page-manual', '', 'https://www.knickgasm.com/collections/grocery-collection-page-manual'),
  ('UK', 'halloween-exclusive-sale', 'halloween-exclusive-sale', '', 'https://www.knickgasm.com/collections/halloween-exclusive-sale'),
  ('UK', 'halloween-exclusives', 'halloween-exclusives', '', 'https://www.knickgasm.com/collections/halloween-exclusives'),
  ('UK', 'halloween-sale', 'halloween-sale', '', 'https://www.knickgasm.com/collections/halloween-sale'),
  ('UK', 'halloween-savings', 'halloween-savings', '', 'https://www.knickgasm.com/collections/halloween-savings'),
  ('UK', 'halloween-treat', 'halloween-treat', '', 'https://www.knickgasm.com/collections/halloween-treat'),
  ('UK', 'halloween-treat-1', 'halloween-treat-1', '', 'https://www.knickgasm.com/collections/halloween-treat-1'),
  ('UK', 'themed-supplements', 'Themed Supplements', '', 'https://www.knickgasm.com/collections/themed-supplements'),
  ('UK', 'themed-sneaker', 'Themed Sneakers', '', 'https://www.knickgasm.com/collections/themed-sneaker'),
  ('UK', 'themed-sneakers-hand-painted', 'Themed Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/themed-sneakers-hand-painted'),
  ('UK', 'themed-sneaker-hand-painted', 'Themed Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/themed-sneaker-hand-painted'),
  ('UK', 'themed-sneaker-bags', 'themed-sneaker-bags', '', 'https://www.knickgasm.com/collections/themed-sneaker-bags'),
  ('UK', 'themed-sneaker-code', 'themed-sneaker-code', '', 'https://www.knickgasm.com/collections/themed-sneaker-code'),
  ('UK', 'holiday-deals', 'holiday-deals', '', 'https://www.knickgasm.com/collections/holiday-deals'),
  ('UK', 'holiday-specials', 'holiday-specials', '', 'https://www.knickgasm.com/collections/holiday-specials'),
  ('UK', 'frontpage', 'Home page', '', 'https://www.knickgasm.com/collections/frontpage'),
  ('UK', 'iced-sneaker', 'Bling Kickss', '', 'https://www.knickgasm.com/collections/iced-sneaker'),
  ('UK', 'iced-crafts', 'iced-crafts', '', 'https://www.knickgasm.com/collections/iced-crafts'),
  ('UK', 'immunity-boosting-sneakers', 'immunity-boosting-sneakers', '', 'https://www.knickgasm.com/collections/immunity-boosting-sneakers'),
  ('UK', 'ingredient-based', 'Ingredient Based', '', 'https://www.knickgasm.com/collections/ingredient-based'),
  ('UK', 'instant-sneaker', 'Instant Mixes', '', 'https://www.knickgasm.com/collections/instant-sneaker'),
  ('UK', 'instant-sneakers', 'Instant Sneakers', '', 'https://www.knickgasm.com/collections/instant-sneakers'),
  ('UK', 'instant-kicks-latte', 'instant-kicks-latte', '', 'https://www.knickgasm.com/collections/instant-kicks-latte'),
  ('UK', 'insulated-range', 'Insulated range', '', 'https://www.knickgasm.com/collections/insulated-range'),
  ('UK', 'insulated-gear', 'Insulated Gear', '', 'https://www.knickgasm.com/collections/insulated-gear'),
  ('UK', 'isabellas-favourite-holiday-sneakers', 'isabellas-favourite-holiday-sneakers', '', 'https://www.knickgasm.com/collections/isabellas-favourite-holiday-sneakers'),
  ('UK', 'isabelles-favourite-sneakers', 'isabelles-favourite-sneakers', '', 'https://www.knickgasm.com/collections/isabelles-favourite-sneakers'),
  ('UK', 'keto-support', 'keto-support', '', 'https://www.knickgasm.com/collections/keto-support'),
  ('UK', 'limited-time-savings', 'limited-time-savings', '', 'https://www.knickgasm.com/collections/limited-time-savings'),
  ('UK', 'hand-painted-sneakers', 'Hand-painted Sneakers', '', 'https://www.knickgasm.com/collections/hand-painted-sneakers'),
  ('UK', 'lunar-new-year', 'lunar-new-year', '', 'https://www.knickgasm.com/collections/lunar-new-year'),
  ('UK', 'marias-favourite-sneakers', 'marias-favourite-sneakers', '', 'https://www.knickgasm.com/collections/marias-favourite-sneakers'),
  ('UK', 'dunks', 'Dunks', '', 'https://www.knickgasm.com/collections/dunks'),
  ('UK', 'mint-green', 'Mint Green', '', 'https://www.knickgasm.com/collections/mint-green'),
  ('UK', 'gifts', 'Most-Loved Sneaker Gifts', '', 'https://www.knickgasm.com/collections/gifts'),
  ('UK', 'mothers-day-2022-gift', 'mothers-day-2022-gift', '', 'https://www.knickgasm.com/collections/mothers-day-2022-gift'),
  ('UK', 'mothers-day-2025', 'mothers-day-2025', '', 'https://www.knickgasm.com/collections/mothers-day-2025'),
  ('UK', 'natalias-favourite-holiday-sneakers', 'natalias-favourite-holiday-sneakers', '', 'https://www.knickgasm.com/collections/natalias-favourite-holiday-sneakers'),
  ('UK', 'natalias-favourite-sneakers', 'natalias-favourite-sneakers', '', 'https://www.knickgasm.com/collections/natalias-favourite-sneakers'),
  ('UK', 'national-lazy-day', 'national-lazy-day', '', 'https://www.knickgasm.com/collections/national-lazy-day'),
  ('UK', 'nepal-black-sneakers', 'Nepal Black Sneakers', '', 'https://www.knickgasm.com/collections/nepal-black-sneakers'),
  ('UK', 'new-arrivals', 'new-arrivals', '', 'https://www.knickgasm.com/collections/new-arrivals'),
  ('UK', 'court-vision-sneakers', 'court-vision-sneakers', '', 'https://www.knickgasm.com/collections/court-vision-sneakers'),
  ('UK', 'occasion-boxes', 'occasion-boxes', '', 'https://www.knickgasm.com/collections/occasion-boxes'),
  ('UK', 'olgas-favorite-sneakers', 'olgas-favorite-sneakers', '', 'https://www.knickgasm.com/collections/olgas-favorite-sneakers'),
  ('UK', 'hightop-sneakers', 'Hightop Sneakers', '', 'https://www.knickgasm.com/collections/hightop-sneakers'),
  ('UK', 'hightop-sneakers-hand-painted', 'Hightop Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/hightop-sneakers-hand-painted'),
  ('UK', 'oops-we-made-too-much-sale', 'oops-we-made-too-much-sale', '', 'https://www.knickgasm.com/collections/oops-we-made-too-much-sale'),
  ('UK', 'oprah-fan-mom', 'oprah-fan-mom', '', 'https://www.knickgasm.com/collections/oprah-fan-mom'),
  ('UK', 'opt-streetwear', 'opt-streetwear', '', 'https://www.knickgasm.com/collections/opt-streetwear'),
  ('UK', 'opt-streetwear-code', 'opt-streetwear-code', '', 'https://www.knickgasm.com/collections/opt-streetwear-code'),
  ('UK', 'organic-black-sneakers', 'Organic Black Sneakers', '', 'https://www.knickgasm.com/collections/organic-black-sneakers'),
  ('UK', 'organic-sneakers', 'Organic Sneakers', '', 'https://www.knickgasm.com/collections/organic-sneakers'),
  ('UK', 'organic-latte-gm', 'organic-latte-gm', '', 'https://www.knickgasm.com/collections/organic-latte-gm'),
  ('UK', 'our-bestsellers-gm', 'our-bestsellers-gm', '', 'https://www.knickgasm.com/collections/our-bestsellers-gm'),
  ('UK', 'pink', 'Pink', '', 'https://www.knickgasm.com/collections/pink'),
  ('UK', 'pipers-favorite-sneakers', 'pipers-favorite-sneakers', '', 'https://www.knickgasm.com/collections/pipers-favorite-sneakers'),
  ('UK', 'prime-day-sale', 'prime-day-sale', '', 'https://www.knickgasm.com/collections/prime-day-sale'),
  ('UK', 'pumpkin-specials', 'pumpkin-specials', '', 'https://www.knickgasm.com/collections/pumpkin-specials'),
  ('UK', 'rachels-favorite-sneakers', 'rachels-favorite-sneakers', '', 'https://www.knickgasm.com/collections/rachels-favorite-sneakers'),
  ('UK', 'robins-favourite-sneakers', 'robins-favourite-sneakers', '', 'https://www.knickgasm.com/collections/robins-favourite-sneakers'),
  ('UK', 'sahara-rose', 'sahara-rose', '', 'https://www.knickgasm.com/collections/sahara-rose'),
  ('UK', 'samplers', 'Samplers', '', 'https://www.knickgasm.com/collections/samplers'),
  ('UK', 'seasonal-change-sneakers', 'seasonal-change-sneakers', '', 'https://www.knickgasm.com/collections/seasonal-change-sneakers'),
  ('UK', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.knickgasm.com/collections/second-flush-2025'),
  ('UK', 'second-flush-sneakers-2023', 'Second Flush Black Sneakers 2023', '', 'https://www.knickgasm.com/collections/second-flush-sneakers-2023'),
  ('UK', 'second-flush', 'second-flush', '', 'https://www.knickgasm.com/collections/second-flush'),
  ('UK', 'second-flush-sale', 'second-flush-sale', '', 'https://www.knickgasm.com/collections/second-flush-sale'),
  ('UK', 'sellers', 'sellers', '', 'https://www.knickgasm.com/collections/sellers'),
  ('UK', 'best-selling-march-2026', 'Shop Our Most Popular Picks', '', 'https://www.knickgasm.com/collections/best-selling-march-2026'),
  ('UK', 'shop-our-bestsellers', 'shop-our-bestsellers', '', 'https://www.knickgasm.com/collections/shop-our-bestsellers'),
  ('UK', 'signature-private-reserve', 'Signature Private Reserve', '', 'https://www.knickgasm.com/collections/signature-private-reserve'),
  ('UK', 'one-of-one', 'One of One', '', 'https://www.knickgasm.com/collections/one-of-one'),
  ('UK', 'one-of-one-sneakers', 'One of One Sneakers 2025', '', 'https://www.knickgasm.com/collections/one-of-one-sneakers'),
  ('UK', 'spices', 'Single Origin Spices', '', 'https://www.knickgasm.com/collections/spices'),
  ('UK', 'skys-the-limit', 'skys-the-limit', '', 'https://www.knickgasm.com/collections/skys-the-limit'),
  ('UK', 'solanges-favourite-holiday-sneakers', 'solanges-favourite-holiday-sneakers', '', 'https://www.knickgasm.com/collections/solanges-favourite-holiday-sneakers'),
  ('UK', 'solanges-favourite-sneakers', 'solanges-favourite-sneakers', '', 'https://www.knickgasm.com/collections/solanges-favourite-sneakers'),
  ('UK', 'solanges-favourite-sneakers-1', 'solanges-favourite-sneakers-1', '', 'https://www.knickgasm.com/collections/solanges-favourite-sneakers-1'),
  ('UK', 'spring-sneakers', 'spring-sneakers', '', 'https://www.knickgasm.com/collections/spring-sneakers'),
  ('UK', 'st-patricks-day-bestsellers', 'st-patricks-day-bestsellers', '', 'https://www.knickgasm.com/collections/st-patricks-day-bestsellers'),
  ('UK', 'st-patricks-day-black-sneakers', 'st-patricks-day-black-sneakers', '', 'https://www.knickgasm.com/collections/st-patricks-day-black-sneakers'),
  ('UK', 'st-patricks-day-kicks-sneakers', 'st-patricks-day-kicks-sneakers', '', 'https://www.knickgasm.com/collections/st-patricks-day-kicks-sneakers'),
  ('UK', 'stainless-steel-range', 'Stainless Steel Range', '', 'https://www.knickgasm.com/collections/stainless-steel-range'),
  ('UK', 'stainless-steel-gear', 'Stainless Steel Gear', '', 'https://www.knickgasm.com/collections/stainless-steel-gear'),
  ('UK', 'lace-up-into-spring', 'lace-up-into-spring', '', 'https://www.knickgasm.com/collections/lace-up-into-spring'),
  ('UK', 'super-saver-bundles', 'Super Saver Bundles', '', 'https://www.knickgasm.com/collections/super-saver-bundles'),
  ('UK', 'superfoods', 'superfoods', '', 'https://www.knickgasm.com/collections/superfoods'),
  ('UK', 'susans-favourite-holiday-sneakers', 'susans-favourite-holiday-sneakers', '', 'https://www.knickgasm.com/collections/susans-favourite-holiday-sneakers'),
  ('UK', 'sneaker-accessories', 'Sneaker Accessories', '', 'https://www.knickgasm.com/collections/sneaker-accessories'),
  ('UK', 'sneaker-bags', 'Lace Sets', '', 'https://www.knickgasm.com/collections/sneaker-bags'),
  ('UK', 'sneaker-carnival-collection', 'Sneaker Carnival Collection', '', 'https://www.knickgasm.com/collections/sneaker-carnival-collection'),
  ('UK', 'sneaker-pods', 'Sneaker Pods', '', 'https://www.knickgasm.com/collections/sneaker-pods'),
  ('UK', 'sneaker-lover-mom', 'sneaker-lover-mom', '', 'https://www.knickgasm.com/collections/sneaker-lover-mom'),
  ('UK', 'travel-collection', 'Travel Collection', '', 'https://www.knickgasm.com/collections/travel-collection'),
  ('UK', 'traveller-mom', 'traveller-mom', '', 'https://www.knickgasm.com/collections/traveller-mom'),
  ('UK', 'trendy-mom', 'trendy-mom', '', 'https://www.knickgasm.com/collections/trendy-mom'),
  ('UK', 'embroidery-collection', 'Embroidery Collection', '', 'https://www.knickgasm.com/collections/embroidery-collection'),
  ('UK', 'embroidery-neon', 'embroidery-neon', '', 'https://www.knickgasm.com/collections/embroidery-neon'),
  ('UK', 'embroidery-themed-sneakers-fb', 'embroidery-themed-sneakers-fb', '', 'https://www.knickgasm.com/collections/embroidery-themed-sneakers-fb'),
  ('UK', 'embroidery-themed-sneakers-gm', 'embroidery-themed-sneakers-gm', '', 'https://www.knickgasm.com/collections/embroidery-themed-sneakers-gm'),
  ('UK', 'embroidery-latte-fb', 'embroidery-latte-fb', '', 'https://www.knickgasm.com/collections/embroidery-latte-fb'),
  ('UK', 'embroidery-superfood-lattes', 'embroidery-superfood-lattes', '', 'https://www.knickgasm.com/collections/embroidery-superfood-lattes'),
  ('UK', 'uk-free-gift', 'uk-free-gift', '', 'https://www.knickgasm.com/collections/uk-free-gift'),
  ('UK', 'uk-products', 'uk-products', '', 'https://www.knickgasm.com/collections/uk-products'),
  ('UK', 'knickgasm-red', 'knickgasm-red', '', 'https://www.knickgasm.com/collections/knickgasm-red'),
  ('UK', 'knickgasm-women-favs', 'knickgasm-women-favs', '', 'https://www.knickgasm.com/collections/knickgasm-women-favs'),
  ('UK', 'valentine-sale', 'valentine-sale', '', 'https://www.knickgasm.com/collections/valentine-sale'),
  ('UK', 'vegan', 'vegan', '', 'https://www.knickgasm.com/collections/vegan'),
  ('UK', 'vegan-1', 'vegan-1', '', 'https://www.knickgasm.com/collections/vegan-1'),
  ('UK', 'streetwear-digest', 'streetwear-digest', '', 'https://www.knickgasm.com/collections/streetwear-digest'),
  ('UK', 'streetwear-enthusiast', 'streetwear-enthusiast', '', 'https://www.knickgasm.com/collections/streetwear-enthusiast'),
  ('UK', 'streetwear-savings-carnival', 'streetwear-savings-carnival', '', 'https://www.knickgasm.com/collections/streetwear-savings-carnival'),
  ('UK', 'white-sneakers', 'White Sneakers', '', 'https://www.knickgasm.com/collections/white-sneakers'),
  ('UK', 'white-sneakers-hand-painted', 'White Sneakers | Hand-painted', '', 'https://www.knickgasm.com/collections/white-sneakers-hand-painted'),
  ('UK', 'winter-sneakers', 'Winter Sneakers', '', 'https://www.knickgasm.com/collections/winter-sneakers'),
  ('UK', 'winter-classics', 'winter-classics', '', 'https://www.knickgasm.com/collections/winter-classics'),
  ('UK', 'yellow', 'yellow', '', 'https://www.knickgasm.com/collections/yellow'),
  ('UK', 'yogaclub', 'yogaclub', '', 'https://www.knickgasm.com/collections/yogaclub'),
  ('UK', 'zodiac-collection', 'zodiac-collection', '', 'https://www.knickgasm.com/collections/zodiac-collection'),
  ('IN', 'founders-day', 'A Decade of Streetwear, Impact & Innovation', '', 'https://www.knickgasm.in/collections/founders-day'),
  ('IN', 'accessories', 'Accessories', '', 'https://www.knickgasm.in/collections/accessories'),
  ('IN', 'all', 'All Products', '', 'https://www.knickgasm.in/collections/all'),
  ('IN', 'all-sneakers-copy', 'All Sneakers', '', 'https://www.knickgasm.in/collections/all-sneakers-copy'),
  ('IN', 'best-sellers', 'Best Sellers', '', 'https://www.knickgasm.in/collections/best-sellers'),
  ('IN', 'black-sneakers', 'Black Sneakers', '', 'https://www.knickgasm.in/collections/black-sneakers'),
  ('IN', 'bundle-collections', 'Bundle-Collection', '', 'https://www.knickgasm.in/collections/bundle-collections'),
  ('IN', 'kicks-sneakers', 'Kicks Sneakers', '', 'https://www.knickgasm.in/collections/kicks-sneakers'),
  ('IN', 'pastel-sneakers', 'Pastel Sneakers', '', 'https://www.knickgasm.in/collections/pastel-sneakers'),
  ('IN', 'deal-of-the-day', 'Deal of the Day', '', 'https://www.knickgasm.in/collections/deal-of-the-day'),
  ('IN', 'first-flush-2025', 'First Flush 2026', '', 'https://www.knickgasm.in/collections/first-flush-2025'),
  ('IN', 'glassware', 'Glassware', '', 'https://www.knickgasm.in/collections/glassware'),
  ('IN', 'green-sneakers', 'Green Sneakers', '', 'https://www.knickgasm.in/collections/green-sneakers'),
  ('IN', 'themed-sneaker', 'Themed Finishes', '', 'https://www.knickgasm.in/collections/themed-sneaker'),
  ('IN', 'holi-the-design-fest', 'Holi - The Design Fest 🥂', '', 'https://www.knickgasm.in/collections/holi-the-design-fest'),
  ('IN', 'iced-crafts', 'Iced Brews', '', 'https://www.knickgasm.in/collections/iced-crafts'),
  ('IN', 'iced-sneakers', 'Bling Kickss', '', 'https://www.knickgasm.in/collections/iced-sneakers'),
  ('IN', 'instant-sneakers', 'Instant Mixes', '', 'https://www.knickgasm.in/collections/instant-sneakers'),
  ('IN', 'insulated-gear', 'Insulated Gear', '', 'https://www.knickgasm.in/collections/insulated-gear'),
  ('IN', 'hand-painted-sneakers', 'Hand-painted Sneakers', '', 'https://www.knickgasm.in/collections/hand-painted-sneakers'),
  ('IN', 'dunks', 'Dunks Sneaker Powder', '', 'https://www.knickgasm.in/collections/dunks'),
  ('IN', 'buy-sneaker-sets-in-india', 'Most-Loved Sneaker Gifts', '', 'https://www.knickgasm.in/collections/buy-sneaker-sets-in-india'),
  ('IN', 'newly-launched', 'Newly Launched', '', 'https://www.knickgasm.in/collections/newly-launched'),
  ('IN', 'hightop-sneakers', 'Hightop Sneakers', '', 'https://www.knickgasm.in/collections/hightop-sneakers'),
  ('IN', 'samplers', 'Samplers', '', 'https://www.knickgasm.in/collections/samplers'),
  ('IN', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.knickgasm.in/collections/second-flush-2025'),
  ('IN', 'sale', 'Share the Joy of Freedom and Festivity', '', 'https://www.knickgasm.in/collections/sale'),
  ('IN', 'one-of-one-2025', 'One of One 2026', '', 'https://www.knickgasm.in/collections/one-of-one-2025'),
  ('IN', 'stainless-steel-gear', 'Stainless Steel Gear', '', 'https://www.knickgasm.in/collections/stainless-steel-gear'),
  ('IN', 'supplements', 'Supplements', '', 'https://www.knickgasm.in/collections/supplements'),
  ('IN', 'sneaker-bags', 'Lace Sets', '', 'https://www.knickgasm.in/collections/sneaker-bags'),
  ('IN', 'test-bundle', 'Test Bundle', '', 'https://www.knickgasm.in/collections/test-bundle'),
  ('IN', 'test-smart-collection', 'TEST Smart Collection', '', 'https://www.knickgasm.in/collections/test-smart-collection'),
  ('IN', 'thoughtful-gifting-bundles', 'Thoughtful Gifting Bundles', '', 'https://www.knickgasm.in/collections/thoughtful-gifting-bundles'),
  ('IN', 'trending-products', 'Trending Products', '', 'https://www.knickgasm.in/collections/trending-products'),
  ('IN', 'embroidery-collection', 'Embroidery collection', '', 'https://www.knickgasm.in/collections/embroidery-collection'),
  ('IN', 'upsell-collection', 'Upsell Collection', '', 'https://www.knickgasm.in/collections/upsell-collection'),
  ('IN', 'valentine-all-sneakers', 'Valentine All Sneakers', '', 'https://www.knickgasm.in/collections/valentine-all-sneakers'),
  ('IN', 'valentinebundle', 'Valentinebundle', '', 'https://www.knickgasm.in/collections/valentinebundle'),
  ('IN', 'white-sneakers', 'White Sneakers', '', 'https://www.knickgasm.in/collections/white-sneakers'),
  ('IN', 'winter-essentials', 'Winter Essentials', '', 'https://www.knickgasm.in/collections/winter-essentials'),
  ('Global', 'coffee-collection', '#1 Rated Coffee Collection', '', 'https://www.knickgasm.com/collections/coffee-collection'),
  ('Global', '2026-first-flush', '2026 First Flush', '', 'https://www.knickgasm.com/collections/2026-first-flush'),
  ('Global', 'founders-day', 'A Decade of Streetwear, Impact & Innovation', '', 'https://www.knickgasm.com/collections/founders-day'),
  ('Global', 'advent-calendar', 'Advent Calendar 2025', '', 'https://www.knickgasm.com/collections/advent-calendar'),
  ('Global', 'all', 'All Products', '', 'https://www.knickgasm.com/collections/all'),
  ('Global', 'best-sellers', 'Best Sellers Of The Season', '', 'https://www.knickgasm.com/collections/best-sellers'),
  ('Global', 'black-sneakers', 'Black Sneakers', '', 'https://www.knickgasm.com/collections/black-sneakers'),
  ('Global', 'best-seller-canada', 'Canada''s Most-Loved Colorways', '', 'https://www.knickgasm.com/collections/best-seller-canada'),
  ('Global', 'kicks-sneakers', 'Kicks Sneakers', '', 'https://www.knickgasm.com/collections/kicks-sneakers'),
  ('Global', 'clearance-sale', 'CLEARANCE SALE', '', 'https://www.knickgasm.com/collections/clearance-sale'),
  ('Global', 'deal-of-the-day-2024', 'Deal of the day', '', 'https://www.knickgasm.com/collections/deal-of-the-day-2024'),
  ('Global', 'first-flush-2025', 'First Flush 2025', '', 'https://www.knickgasm.com/collections/first-flush-2025'),
  ('Global', 'best-seller-germany', 'Germany''s Most-Loved Colorways', '', 'https://www.knickgasm.com/collections/best-seller-germany'),
  ('Global', 'glassware', 'Glassware', '', 'https://www.knickgasm.com/collections/glassware'),
  ('Global', 'green-sneakers', 'Green Sneakers', '', 'https://www.knickgasm.com/collections/green-sneakers'),
  ('Global', 'themed-sneakers', 'Themed Sneakers', '', 'https://www.knickgasm.com/collections/themed-sneakers'),
  ('Global', 'instant-sneaker', 'Instant Mixes', '', 'https://www.knickgasm.com/collections/instant-sneaker'),
  ('Global', 'drink-ware', 'Insulated Gear', '', 'https://www.knickgasm.com/collections/drink-ware'),
  ('Global', 'insulated-gear', 'Insulated Gear', '', 'https://www.knickgasm.com/collections/insulated-gear'),
  ('Global', 'best-seller-italy', 'Italy’s Most-Loved Colorways', '', 'https://www.knickgasm.com/collections/best-seller-italy'),
  ('Global', 'hand-painted-sneakers', 'Hand-painted Sneakers', '', 'https://www.knickgasm.com/collections/hand-painted-sneakers'),
  ('Global', 'dunks', 'Dunks', '', 'https://www.knickgasm.com/collections/dunks'),
  ('Global', 'gifts', 'Most Loved Gifts Of The Season', '', 'https://www.knickgasm.com/collections/gifts'),
  ('Global', 'new-arrivals', 'New Arrivals', '', 'https://www.knickgasm.com/collections/new-arrivals'),
  ('Global', 'hightop-sneakers', 'Hightop Sneakers', '', 'https://www.knickgasm.com/collections/hightop-sneakers'),
  ('Global', 'samplers', 'Samplers', '', 'https://www.knickgasm.com/collections/samplers'),
  ('Global', 'second-flush-2025', 'Second Flush 2025', '', 'https://www.knickgasm.com/collections/second-flush-2025'),
  ('Global', 'one-of-one', 'One of One 2025', '', 'https://www.knickgasm.com/collections/one-of-one'),
  ('Global', 'stainless-steel-range', 'Stainless Steel Gear', '', 'https://www.knickgasm.com/collections/stainless-steel-range'),
  ('Global', 'lace-up-into-spring', 'Lace-up Into Spring 🌿', '', 'https://www.knickgasm.com/collections/lace-up-into-spring'),
  ('Global', 'sale', 'SUPER SAVER SNEAKER COLLECTION', '', 'https://www.knickgasm.com/collections/sale'),
  ('Global', 'sneaker-wares', 'Sneaker Accessories', '', 'https://www.knickgasm.com/collections/sneaker-wares'),
  ('Global', 'sneaker-bags', 'Lace Sets', '', 'https://www.knickgasm.com/collections/sneaker-bags'),
  ('Global', 'best-seller-uk', 'The UK''s Most-Loved Colorways', '', 'https://www.knickgasm.com/collections/best-seller-uk'),
  ('Global', 'white-sneakers', 'White Sneakers', '', 'https://www.knickgasm.com/collections/white-sneakers')
ON CONFLICT (market, handle) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, url=EXCLUDED.url, refreshed_at=now();